[package]
name = "vtree_markup"
version = "0.0.0"
authors = ["Thomas Heck <t@b128.net>"]

[dependencies]
quote = "0.3"
syn = {version = "0.11.6", features = ["full"]}
synom = "0.11.0"

[lib]
proc-macro = true
crate-type = ["proc-macro"]
